### ISSUE TITLE
Nginx error:  failed to load external Lua file 

### ISSUE THREAD

**Issue by mo7och** [dhoffend/lua-nginx-privacyidea#1]
Greeatings!
We have trubles with configurating lua-nginx-privacyidea stack.

With this nginx host conf:

`server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;
        root /var/www/html;

```
    index index.html index.htm index.nginx-debian.html;
    server_name nginx1 nginx1.local localhost;
    location / {
            try_files $uri $uri/ =404;
             set $privacyidea_redis_host "127.0.0.1";
             set $privacyidea_redis_post 6379;
             set $privacyidea_ttl 900;
             set $privacyidea_uri "/privacyidea-validate-check";
             set $privacyidea_salt "some random string as hmac salt";
             set $privacyidea_http_realm "Secure zone (use PIN + OTP)";
            access_by_lua_file '/var/www/html/privacyidea.lua';
    }
    location /privacyidea-validate-check {
            proxy_pass https://privacyidea_server/validate/check;
    }
```

}`

We have this output in error log:

> 2016/02/02 11:12:02 [error] 12449#12449: *4 failed to load external Lua file "/var/www/html/privacyidea.lua": /var/www/html/privacyidea.lua:5: unexpected symbol near '<', client: 10.10.15.149, server: nginx1, request: "GET /favicon.ico HTTP/1.1", host: "nginx1", referrer: "http://nginx1/"

What we doing wrong?

**Comment by dhoffend** [comment]
Sorry for the late answer. I just tested my example setup and it still works. But would you be so kind and check the contents of your lua file?

Cause your error message indicates that there's a problem with a character ">" in line 5 .. Which should not be the case:

I'm also wondering why you placed the lua file in the webroot directory. That doesn't make any sense to me cause it's a backend only file.

Here is my example configuration without any quotes.

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                set $privacyidea_ttl 30;
                set $privacyidea_http_realm "Secure zone (use PIN + OTP)";
                access_by_lua_file /etc/nginx/lua-nginx-privacyidea/privacyidea.lua;
                try_files $uri $uri/ =404;
        }
        location /privacyidea-validate-check {
                internal;
                proxy_pass http://10.128.38.7/validate/check;
        }
}
```

Here is the software that I've installed on my test machine:

```
root@nginx-auth:~# dpkg -l | egrep 'nginx|redis|lua-'
ii  lua-cjson:amd64                2.1.0+dfsg-2                amd64        JSON parser/encoder for Lua
ii  lua-nginx-redis                0.20-1                      all          Pure Lua redis client driver for the nginx embedded Lua language
ii  nginx-common                   1.6.2-5                     all          small, powerful, scalable web/proxy server - common files
ii  nginx-extras                   1.6.2-5                     amd64        nginx web/proxy server (extended version)
ii  redis-server                   2:2.8.17-1+deb8u1           amd64        Persistent key-value database with network interface
ii  redis-tools                    2:2.8.17-1+deb8u1           amd64        Persistent key-value database with network interface (client)

```

**Comment by dhoffend** [comment]
Maybe you tried to download the file via wget and in the end you received a html file instead of the lua script you wanted to fetch.

Either download it as raw file or check it out via git

**Comment by mo7och** [comment]
Daniel, thank you for your reply.

Problems was with:
1. We used privacyidea.lua file with errors (after wrong downloading).
2. We used wrong software versions.

Now we fixed all issues. 
Thank you! Have a nice day!

PS
The lua file placed in the webroot directory just for test.

**Comment by dhoffend** [comment]
Thanks for your reply
