### ISSUE TITLE
invalid authentication: wrong otp pin while sending to client

### ISSUE THREAD

**Issue by ciroiriarte** [dhoffend/lua-nginx-privacyidea#2]
Hi!, 

I'm testing your script right now, and found the following errors in nginx logs while trying to authenticate:

==> /var/log/nginx/error.log <==
2018/04/23 05:29:33 [error] 678#678: *42 [lua] privacyidea.lua:161: authenticate(): [ciriarte] invalid authentication: wrong otp pin while sending to client, client: 10.x.y.z, server: _, request: "GET / HTTP/1.1", host: "mfa-web01.lan"

The privacy idea server has an LDAP backend,with SMS and U2F as second factor. I enrolled the U2F token with and without PIN (not sure if it's needed for U2F, and it's bothersome for the end user having to remember another thing)

I get the same wrong otp pin, either enrolling the token with ot without PIN.

PrivacyIDEA version: 2.17

Any hints?

**Comment by cornelinux** [comment]
Note: both - SMS and U2F are challenge response tokens. I am not sure if this plugin supports these mechanisms!

**Comment by dhoffend** [comment]
This plugin was designed to be used with Password + otp. I haven’t used it with 2 factors. I guess that would require additional work and thoughts

**Comment by cornelinux** [comment]
Being no lua expert the code looks (https://github.com/dhoffend/lua-nginx-privacyidea/blob/master/privacyidea.lua#L100) like it works with "single shot" authentication devices like key fob tokens, OTP yubikeys, smartphone apps.

@ciroiriarte Using SMS or U2F you first need to trigger a challenge with the PIN/LDAP password. Take a look at the API and the "transaction_id". You would have to "ask" for the otp value sent via SMS and then send it again to privacyIDEA. You would have to enhance the code accordingly.

**Comment by Elf36** [comment]
Is SMS still not OK ? is there any way to overcome this with challenge response via NGINX ?

**Comment by dhoffend** [comment]
This plugin is a one shot authentication that can work together with http basic authentication. It takes the password plus otp token (generated on your smartphone app).

If you want to use sms otp authentication you need to integrate this workflow into your application login logic, because http auth doesn't support a login workflow while waiting for the sms to arrive and to be entered in a second input form/popup or whatever.

**Comment by Elf36** [comment]
what do you suggest them for https auth with sms ?

its tricky I suppose

**Comment by cornelinux** [comment]
The explanation by @dhoffend is actually spot on!

However, if you really need to do basic authentication with SMS, you can do it in a very nasty way:

1. Authenticate with *username* and *pin or password*. This will trigger the sending of the SMS. However basic auth will fail.
2. Try to do basic authentication again, but this time with *username* and *PIN+OTP* (which was sent via SMS). 

So the PIN and the OTP value from the SMS in one step actually allows you to do single shot auth. However, not very convenient.

**Comment by Elf36** [comment]
I guess we can use the strong auth plugin ? With Wordpress ?
